version: "3.3"
services:
        adguardhome:
                image: adguard/adguardhome
                container_name: adguardhome
                ports:
                        - 53:53/tcp
                        - 53:53/udp
                        - 853:853/tcp
                        - 3000:3000/tcp
                volumes:
                        - /home/deepak/docker/volumes/adguardhome/work:/opt/adguardhome/work
                        - /home/deepak/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
                restart: unless-stopped
