version: '3.3'
services:
        adguardhome:
                image: adguard/adguardhome
                container_name: adguardhome
               #ports:
                volumes:
                        - /home/deepak/docker/volumes/adguardhome/work:/opt/adguardhome/work
                        - /home/deepak/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
                networks:
                        asgard:
                                ipv4_address: 192.168.1.250
networks:
        asgard:
                external: true
